
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.ins_radicacion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "zsn_insradica", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_43A6415773913812E1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710")
public class ZsnInsradica
    extends Service
{

    private final static URL ZSNINSRADICA_WSDL_LOCATION;
    private final static WebServiceException ZSNINSRADICA_EXCEPTION;
    private final static QName ZSNINSRADICA_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "zsn_insradica");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_43A6415773913812E1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZSNINSRADICA_WSDL_LOCATION = url;
        ZSNINSRADICA_EXCEPTION = e;
    }

    public ZsnInsradica() {
        super(__getWsdlLocation(), ZSNINSRADICA_QNAME);
    }

    public ZsnInsradica(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ZWSVURINSRADICA
     */
    @WebEndpoint(name = "zbn_insradica")
    public ZWSVURINSRADICA getZbnInsradica() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "zbn_insradica"), ZWSVURINSRADICA.class);
    }

    private static URL __getWsdlLocation() {
        if (ZSNINSRADICA_EXCEPTION!= null) {
            throw ZSNINSRADICA_EXCEPTION;
        }
        return ZSNINSRADICA_WSDL_LOCATION;
    }

}
