
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_updstatus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "zsn_updstatus", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_875A415773913812E1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710")
public class ZsnUpdstatus
    extends Service
{

    private final static URL ZSNUPDSTATUS_WSDL_LOCATION;
    private final static WebServiceException ZSNUPDSTATUS_EXCEPTION;
    private final static QName ZSNUPDSTATUS_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "zsn_updstatus");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_875A415773913812E1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZSNUPDSTATUS_WSDL_LOCATION = url;
        ZSNUPDSTATUS_EXCEPTION = e;
    }

    public ZsnUpdstatus() {
        super(__getWsdlLocation(), ZSNUPDSTATUS_QNAME);
    }

    public ZsnUpdstatus(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ZWSVURUPDSTATUS
     */
    @WebEndpoint(name = "zbn_updstatus")
    public ZWSVURUPDSTATUS getZbnUpdstatus() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "zbn_updstatus"), ZWSVURUPDSTATUS.class);
    }

    private static URL __getWsdlLocation() {
        if (ZSNUPDSTATUS_EXCEPTION!= null) {
            throw ZSNUPDSTATUS_EXCEPTION;
        }
        return ZSNUPDSTATUS_WSDL_LOCATION;
    }

}
