
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_updstatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ZWSVUR_UPDSTATUS", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
public interface ZWSVURUPDSTATUS {


    /**
     * 
     * @param iNROLIQ
     * @param eRETURN
     * @param iESTADO
     * @param eMESSAGE
     */
    @WebMethod(operationName = "ZPSCDFM_VUR_UPDSTATUS")
    @RequestWrapper(localName = "ZPSCDFM_VUR_UPDSTATUS", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_updstatus.ZPSCDFMVURUPDSTATUS")
    @ResponseWrapper(localName = "ZPSCDFM_VUR_UPDSTATUSResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_updstatus.ZPSCDFMVURUPDSTATUSResponse")
    public void zpscdfmVURUPDSTATUS(
        @WebParam(name = "I_ESTADO", targetNamespace = "")
        String iESTADO,
        @WebParam(name = "I_NROLIQ", targetNamespace = "")
        String iNROLIQ,
        @WebParam(name = "E_MESSAGE", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMESSAGE,
        @WebParam(name = "E_RETURN", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> eRETURN);

}
