
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_detail_method;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "zsn_getdetail", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_7F5B415773912712E1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710")
public class ZsnGetdetail
    extends Service
{

    private final static URL ZSNGETDETAIL_WSDL_LOCATION;
    private final static WebServiceException ZSNGETDETAIL_EXCEPTION;
    private final static QName ZSNGETDETAIL_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "zsn_getdetail");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_7F5B415773912712E1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZSNGETDETAIL_WSDL_LOCATION = url;
        ZSNGETDETAIL_EXCEPTION = e;
    }

    public ZsnGetdetail() {
        super(__getWsdlLocation(), ZSNGETDETAIL_QNAME);
    }

    public ZsnGetdetail(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ZwsvurGetdetail
     */
    @WebEndpoint(name = "zbn_getdetail")
    public ZwsvurGetdetail getZbnGetdetail() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "zbn_getdetail"), ZwsvurGetdetail.class);
    }

    private static URL __getWsdlLocation() {
        if (ZSNGETDETAIL_EXCEPTION!= null) {
            throw ZSNGETDETAIL_EXCEPTION;
        }
        return ZSNGETDETAIL_WSDL_LOCATION;
    }

}
