
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_detail_method;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "zwsvur_getdetail", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_D5393857F156F52CE1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710")
public class ZwsvurGetdetail_Service
    extends Service
{

    private final static URL ZWSVURGETDETAIL_WSDL_LOCATION;
    private final static WebServiceException ZWSVURGETDETAIL_EXCEPTION;
    private final static QName ZWSVURGETDETAIL_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "ZWSVUR_GETDETAIL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_D5393857F156F52CE1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSVURGETDETAIL_WSDL_LOCATION = url;
        ZWSVURGETDETAIL_EXCEPTION = e;
    }

    public ZwsvurGetdetail_Service() {
        super(__getWsdlLocation(), ZWSVURGETDETAIL_QNAME);
    }

    public ZwsvurGetdetail_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ZwsvurGetdetail
     */
    @WebEndpoint(name = "zwsvur_getdetail")
    public ZwsvurGetdetail getZwsvurGetdetail() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "zwsvur_getdetail"), ZwsvurGetdetail.class);
    }

    private static URL __getWsdlLocation() {
        if (ZWSVURGETDETAIL_EXCEPTION!= null) {
            throw ZWSVURGETDETAIL_EXCEPTION;
        }
        return ZWSVURGETDETAIL_WSDL_LOCATION;
    }

}
