
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_detail_method;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "zwsvur_getdetail", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
public interface ZwsvurGetdetail {


    /**
     * 
     * @param iNROLIQ
     * @param eDETAIL
     * @param eHEADER
     */
    @WebMethod(operationName = "ZPSCDFM_VUR_GETDETAIL")
    @RequestWrapper(localName = "ZPSCDFM_VUR_GETDETAIL", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_detail_method.ZPSCDFMVURGETDETAIL")
    @ResponseWrapper(localName = "ZPSCDFM_VUR_GETDETAILResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_detail_method.ZPSCDFMVURGETDETAILResponse")
    public void zpscdfmVURGETDETAIL(
        @WebParam(name = "I_NROLIQ", targetNamespace = "")
        String iNROLIQ,
        @WebParam(name = "E_DETAIL", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZPSCDTTVURDETAIL> eDETAIL,
        @WebParam(name = "E_HEADER", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZPSCDPRNCAB> eHEADER);

}
