
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_payment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "zsn_payment", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_205A415773913812E1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710")
public class ZsnPayment
    extends Service
{

    private final static URL ZSNPAYMENT_WSDL_LOCATION;
    private final static WebServiceException ZSNPAYMENT_EXCEPTION;
    private final static QName ZSNPAYMENT_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "zsn_payment");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_205A415773913812E1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZSNPAYMENT_WSDL_LOCATION = url;
        ZSNPAYMENT_EXCEPTION = e;
    }

    public ZsnPayment() {
        super(__getWsdlLocation(), ZSNPAYMENT_QNAME);
    }

    public ZsnPayment(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ZwsvurPayment
     */
    @WebEndpoint(name = "zbn_payment")
    public ZwsvurPayment getZbnPayment() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "zbn_payment"), ZwsvurPayment.class);
    }

    private static URL __getWsdlLocation() {
        if (ZSNPAYMENT_EXCEPTION!= null) {
            throw ZSNPAYMENT_EXCEPTION;
        }
        return ZSNPAYMENT_WSDL_LOCATION;
    }

}
