
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "zwsvur_payment", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
public interface ZwsvurPayment {


    /**
     * 
     * @param iNROLIQ
     * @param eRETURN
     * @param iVALOR
     * @param iHORARECAUDO
     * @param iFECHARECAUDO
     * @param iCUENTABCO
     * @param eMESSAGE
     */
    @WebMethod(operationName = "ZPSCDFM_VUR_PAYMENT")
    @RequestWrapper(localName = "ZPSCDFM_VUR_PAYMENT", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_payment.ZPSCDFMVURPAYMENT")
    @ResponseWrapper(localName = "ZPSCDFM_VUR_PAYMENTResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_payment.ZPSCDFMVURPAYMENTResponse")
    public void zpscdfmVURPAYMENT(
        @WebParam(name = "I_CUENTA_BCO", targetNamespace = "")
        String iCUENTABCO,
        @WebParam(name = "I_FECHA_RECAUDO", targetNamespace = "")
        String iFECHARECAUDO,
        @WebParam(name = "I_HORA_RECAUDO", targetNamespace = "")
        String iHORARECAUDO,
        @WebParam(name = "I_NROLIQ", targetNamespace = "")
        String iNROLIQ,
        @WebParam(name = "I_VALOR", targetNamespace = "")
        String iVALOR,
        @WebParam(name = "E_MESSAGE", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMESSAGE,
        @WebParam(name = "E_RETURN", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Integer> eRETURN);

}
