
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.vur_payment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "zwsvur_payment", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_E0D73857F056F42CE1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710")
public class ZwsvurPayment_Service
    extends Service
{

    private final static URL ZWSVURPAYMENT_WSDL_LOCATION;
    private final static WebServiceException ZWSVURPAYMENT_EXCEPTION;
    private final static QName ZWSVURPAYMENT_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "zwsvur_payment");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://lavoragine.elvalle.com:8000/sap/bc/srt/wsdl/bndg_E0D73857F056F42CE1000000C0A8C847/wsdl11/allinone/standard/document?sap-client=710");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZWSVURPAYMENT_WSDL_LOCATION = url;
        ZWSVURPAYMENT_EXCEPTION = e;
    }

    public ZwsvurPayment_Service() {
        super(__getWsdlLocation(), ZWSVURPAYMENT_QNAME);
    }

    public ZwsvurPayment_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ZwsvurPayment
     */
    @WebEndpoint(name = "zwsvur_payment")
    public ZwsvurPayment getZwsvurPayment() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "zwsvur_payment"), ZwsvurPayment.class);
    }

    private static URL __getWsdlLocation() {
        if (ZWSVURPAYMENT_EXCEPTION!= null) {
            throw ZWSVURPAYMENT_EXCEPTION;
        }
        return ZWSVURPAYMENT_WSDL_LOCATION;
    }

}
