
package co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_list_method;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "zwsvur_getlist", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
public interface ZwsvurGetlist {


    /**
     * 
     * @param iDATE
     * @return
     *     returns co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_list_method.ZPSCDTTVURLIST
     */
    @WebMethod(operationName = "ZPSCDFM_VUR_GETLIST")
    @WebResult(name = "E_LIST", targetNamespace = "")
    @RequestWrapper(localName = "ZPSCDFM_VUR_GETLIST", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_list_method.ZPSCDFMVURGETLIST")
    @ResponseWrapper(localName = "ZPSCDFM_VUR_GETLISTResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "co.com.realtech.mariner.model.ejb.ws.sap.mappers.get_list_method.ZPSCDFMVURGETLISTResponse")
    public ZPSCDTTVURLIST zpscdfmVURGETLIST(
        @WebParam(name = "I_DATE", targetNamespace = "")
        String iDATE);

}
